### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by Parikshit-Hooda** [aquasecurity/deployments#16]
Hi!
This repo needs a license file!
I would love to add one as part of hacktoberfest!
You could tell me which license I should add or I could add `GNU Affero General Public License v3.0` as is the case with the `Trivy` repo

**Comment by rshmiel** [comment]
@Parikshit-Hooda thanks for reporting
https://github.com/aquasecurity/deployments/blob/master/LICENSE
