### ISSUE TITLE
Incorrectly refers aqua-db instead of aqua-audit-db

### ISSUE THREAD

**Issue by veeshall** [aquasecurity/deployments#171]
https://github.com/aquasecurity/deployments/blob/f36093baaa3b3df053a1a1f5b761456fb481fdd7/orchestrators/kubernetes/manifests/aqua_csp_006_server_deployment/aqua_server_deployment_managed_db.yaml#L182

Incorrectly refers aqua-db instead of aqua-audit-db in aqua-gateway

**Comment by rshmiel** [comment]
Fixed. @veeshall thanks for reporting
