### ISSUE TITLE
K8s Quick-Start Host Path Guide audit-db service typo

### ISSUE THREAD

**Issue by rkwa-dan** [aquasecurity/deployments#198]
Line 256 in the 6.0 and 6.2 yaml

https://github.com/aquasecurity/deployments/blob/6.0/orchestrators/kubernetes/quick_start/aqua-csp-quick-hostpath.yaml  

and in the 6.2 yaml 
https://github.com/aquasecurity/deployments/blob/6.2/orchestrators/kubernetes/quick_start/aqua-csp-quick-hostpath.yaml

needs modifying from

  name: aqua-db   

to 
 name: aqua-db-audit 

otherwise the deployment of the service for aqua-db-audit fails.

**Comment by rshmiel** [comment]
fixed,
