### ISSUE TITLE
Base64 aqua-enforcer-token secret

### ISSUE THREAD

**Issue by ericgomes56** [aquasecurity/deployments#250]
Noticed that Base64 doesn't work in this aqua-enforcer-token secret, but clear-text does, yet we say on #L3 the token needs to be b64.

Can we remove #L3 or fix to use b64 as we do with our Helm Enforcer deploy?

**Comment by KoppulaRajender** [comment]
Hi @ericgomes56, Creating token secrets from other technologies might have encodes twice with base64 so that we have removed in helm, but here in yamls will get an error if we create secret from clear-text string,

thanks for reporting, closing this issue.
