### ISSUE TITLE
PostgreSQL version in template is not supported

### ISSUE THREAD

**Issue by masutaro99** [aquasecurity/deployments#359]
Hi,
I tried to create Aqua Console with template in deployments/server/ecs/cloudformation/aqua-ecs-fargate. 
But, the following error occurred.
Cannot find version 11.9 for postgres (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 1d0cf3c3-a21b-49b4-967a-fc71e9cbd5d3; Proxy: null)
I upgraded the version of PostgreSQL embedded in the lines 828 and 853 to 11.12 and it worked.
Would you please fix it if possible.

**Comment by takakuni-classmethod** [comment]
@masutaro99 

Hello,
I have sent you a pull request as the same error occurred.(#380)
As you said, it seems that PostgreSQL on RDS currently supports 11.2 or later versions.
